# Functions to use for online experiments with jsPsych on qpsy.de
# General Psychology II // Department Psychology LMU
# Dr. Moritz Dechamps

#' Load Experimental Files from Server
#'
#' Read all results files (.csv) from the server and write to dataframe
#' @param exp String. The name of the data folder of the experiment to be loaded.
#' @param subdirs Logical. Should subdirectories be considered?
#' @param splitreponse Logical. Should survey responses be automatically written into separate columns?
#' @return Dataframe containing all trials of the combined result files.
#' @examples
#' myexp <- loadexp("myexp")
#' @export

loadexp <- function(exp, subdirs=TRUE, splitresponse=TRUE){

  #read the page
  burl <- "https://qpsy.de/data/"
  url <- paste0(burl,exp,"/")
  page <- rvest::read_html(url)

  #find the hrefs attributes which contain ".csv"
  filenames <- rvest::html_elements(page, xpath = ".//a[contains(@href, '.csv')]") %>% rvest::html_text()

  #look for subdirectories
  if(subdirs == TRUE){
    #list subdirectories
    folders <- rvest::html_elements(page, xpath = ".//a[contains(@href, '/')]") %>% rvest::html_text()
    #exclude "Parent directory"
    folders <- folders[-1]

    if(length(folders > 0)){
      for (f in folders){
        tmp <- .rff(paste0(exp,"/",f))
        if(length(tmp)>0) tmp <- paste0(f,tmp)
        filenames <- append(filenames, tmp)
      }

    }
  }


  links <- paste0(url, filenames)
  links <- gsub(" ", "%20", links)

  raw <- pbapply::pblapply(links, data.table::fread, showProgress = FALSE)
  out <- data.table::rbindlist(raw, id="file", fill=T)

  # fix double quotes on JSON input
  if("response" %in% colnames(out)) out$response <- gsub("\"\"", "\"", out$response)
  if("responses" %in% colnames(out)) out$responses <- gsub("\"\"", "\"", out$responses)
  if("view_history" %in% colnames(out)) out$view_history <- gsub("\"\"", "\"", out$view_history)

  if(splitresponse == TRUE){
    out <- splitresponse(out)
  }

  out
}



# Helper function: Read files recursively

.rff <- function(exp){
  burl <- "https://qpsy.de/data/"
  url <- paste0(burl,exp,"/")
  page <- rvest::read_html(url)

  #find all .csv files
  filenames <- rvest::html_elements(page, xpath = ".//a[contains(@href, '.csv')]") %>% rvest::html_text()

  #list subdirectories
  folders <- rvest::html_elements(page, xpath = ".//a[contains(@href, '/')]") %>% rvest::html_text()
  #exclude "Parent directory"
  folders <- folders[-1]

  if(length(folders > 0)){
    for (f in folders){
      tmp <- rff(paste0(exp,"/",f))
      if(length(tmp)>0) tmp <- paste0(f,tmp)
      filenames <- append(filenames, tmp)
    }

  }
  filenames
}


#' Write responses into variables.
#'
#' Write all answers from the "response"-column generated by a survey-plugin into individual variables.
#' @return Generates new variables (columns) named after the question and storing the given responses.
#' @examples
#' survey <- splitresponse(myexp)
#'
#' survey <- myexp %>%
#'   filter(trial_part == "survey") %>%
#'   splitresponse()
#'
#' @export

splitresponse <- function(data){
  if(!("response" %in% colnames(data))) stop("Dataframe does not contain a \"response\" column")

  message("Splitting responses...")
  data$line <- as.numeric(row.names(data))

  r <- data %>%
    dplyr::filter(grepl("\\{\"",response)) %>% #only lines that contain JSON responses
    dplyr::mutate(
      tmp = jsonlite::stream_in(textConnection(response), simplifyDataFrame = FALSE),
      tmp = lapply(tmp, dplyr::bind_cols)
    ) %>%
    tidyr::unnest(tmp) %>%
    dplyr::select(line:last_col()) #select only new variables

  dplyr::left_join(data, r, by="line") %>%
    dplyr::select(-c(line,response))
}


