# Functions to use for online experiments with jsPsych on qpsy.de
# General Psychology II // Department Psychology LMU
# Dr. Moritz Dechamps

#' Load Experimental Files from Server
#'
#' Read all results files (.csv) from the server and write to dataframe
#' @param exp String. The name of the data folder of the experiment to be loaded.
#' @param subdirs Logical. Should subdirectories be considered? 
#' @return Dataframe containing all trials of the combines result files
#' @examples
#' myexp <- loadexp("myexp")
#' @export

loadexp <- function(exp, subdirs=TRUE){

  #read the page
  burl <- "https://qpsy.de/data/"
  url <- paste0(burl,exp,"/")
  page <- rvest::read_html(url)

  #find the hrefs attributes which contain ".csv"
  filenames <- rvest::html_elements(page, xpath = ".//a[contains(@href, '.csv')]") %>% rvest::html_text()
  
  #look for subdirectories
  if(subdirs == TRUE){
    #list subdirectories
    folders <- rvest::html_elements(page, xpath = ".//a[contains(@href, '/')]") %>% rvest::html_text()
    #exclude "Parent directory"
    folders <- folders[-1]
    
    if(length(folders > 0)){
      for (f in folders){
        tmp <- .rff(paste0(exp,"/",f))
        if(length(tmp)>0) tmp <- paste0(f,tmp)
        filenames <- append(filenames, tmp)
      }
      
    }
  }
  
  
  links <- paste0(url, filenames) %>%
    str_replace_all(" ", "%20")

  raw <- lapply(links, fread)
  data.table::rbindlist(raw, id="file", fill=T) %>%
    mutate(
      response=gsub("\"\"", "\"", response),
      view_history=gsub("\"\"", "\"", view_history)
      )
}



# Helper function: Read files recursively

.rff <- function(exp){
  burl <- "https://qpsy.de/data/"
  url <- paste0(burl,exp,"/")
  page <- rvest::read_html(url)

  #find all .csv files
  filenames <- rvest::html_elements(page, xpath = ".//a[contains(@href, '.csv')]") %>% rvest::html_text()

  #list subdirectories
  folders <- rvest::html_elements(page, xpath = ".//a[contains(@href, '/')]") %>% rvest::html_text()
  #exclude "Parent directory"
  folders <- folders[-1]

  if(length(folders > 0)){
    for (f in folders){
      tmp <- rff(paste0(exp,"/",f))
      if(length(tmp)>0) tmp <- paste0(f,tmp)
      filenames <- append(filenames, tmp)
    }

  }
  filenames
}


#' Write responses into variables.
#'
#' Write all answers from the "response"-column generated by a survey-plugin into individual variables.
#' @return Generates new variables (columns) named after the question and storing the given responses.
#' @examples
#' demo <- myexp %>%
#'   filter(trial_part="demographics") %>%
#'   splitresponse()
#' @export

splitresponse <- function(data){
  data %>%
    mutate(
      tmp = jsonlite::stream_in(textConnection(response), simplifyDataFrame = FALSE),
      tmp = lapply(tmp, bind_cols)
    ) %>%
      unnest(tmp)
}


